### ISSUE TITLE
依赖库

### ISSUE THREAD

**Issue by xxmbaobao** [cundong/ZhihuPaper#6]
直接下载下来，会需要好多库，你给的依赖库链接都是android studio项目的 怎么样才能放到你的项目里？感谢了。

**Comment by wtjandjay** [comment]
哦 没eclipse 版的吗

**Comment by cundong** [comment]
所依赖的工程都是GitHub上开源的，大部分使用Android Studio开发，但由于ZhihuPaper项目是使用Eclipse开发的，我就自己转了一下，你也自己转一下吧。

**Comment by wtjandjay** [comment]
嗯好的谢谢 发自网易邮箱大师 在2015年03月04日 09:50 ，Cundong写道： 所依赖的工程都是GitHub上开源的，大部分使用Android Studio开发，但由于ZhihuPaper项目是使用Eclipse开发的，我就自己转了一下，你也自己转一下吧。 — Reply to this email directly or view it on GitHub.
