### ISSUE TITLE
新手问个问题

### ISSUE THREAD

**Issue by jymgongzuo** [cundong/ZhihuPaper#8]
我是一个android新手，刚刚找到这个工程觉得非常有学习的价值，所以直接下载了您的代码，但是在

到eclipse中发现报错。后来发现是没引入photoview、Crouton等工程，但是从photoview下载的代码是android stdio 编译的，在eclipse中又是报错，所以请问这个问题怎么解决呢？

因为是新手，虽然这样的问题比较低级，但是还是希望你们有空的时候能帮我解答一下。谢谢

**Comment by xxmbaobao** [comment]
用android studio 吧 ，如果用eclipse就下载所有引用的库，但是好多库都已经用android studio 需要你转成eclipse 比较麻烦

**Comment by cundong** [comment]
没问题！
你去:https://github.com/cundong/ZhihuPaper/issues
创建一个issue
我统一回答一下。

在 2015年4月21日 上午10:22，jymgongzuo <notifications@github.com>写道：

> 我是一个android新手，刚刚找到这个工程觉得非常有学习的价值，所以直接下载了您的代码，但是在
>
> 到eclipse中发现报错。后来发现是没引入photoview、Crouton等工程，但是从photoview下载的代码是android stdio
> 编译的，在eclipse中又是报错，所以请问这个问题怎么解决呢？
>
> 因为是新手，虽然这样的问题比较低级，但是还是希望你们有空的时候能帮我解答一下。谢谢
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cundong/ZhihuPaper/issues/8>.
>



-- 
沉舟侧畔千帆过,病树前头万木春~

**Comment by jymgongzuo** [comment]
好的，我再新建一个问题哈  谢谢

**Comment by cundong** [comment]
http://blog.it985.com/1808.html
http://my.oschina.net/cheneywangc/blog/192381
找了两篇文章给你
