### ISSUE TITLE
关于如何正确导入工程到Eclipse开发环境中问题

### ISSUE THREAD

**Issue by jymgongzuo** [cundong/ZhihuPaper#9]
作为一个android的新手，在github中找了很久才找到一个适合学习的开源的app应用很不容易。同时也因为水平较低，将下载的代码导入Eclipse开发环境中会出现如下问题，所以再次请教一下。

1.从红色区域下载到本工程的代码
![1](https://cloud.githubusercontent.com/assets/5999112/7245376/c967cf0a-e81c-11e4-85e8-c1ee3b5ff7f8.png)

2.导入到Eclipse中出现如下问题：发现是没有引用响应的工程
![3](https://cloud.githubusercontent.com/assets/5999112/7245394/1aa7f2be-e81d-11e4-8db4-8fa759b6994c.png)

3.然后根据知乎日报主页介绍中的给出的连接，到相应的开源框架中发现它们大部分都是使用
android stdio进行编译的，将下载的开源框架导入到Eclipse工程中发现很多都会报错
![4](https://cloud.githubusercontent.com/assets/5999112/7245400/44b81b74-e81d-11e4-8990-1de257fa2c55.png)

希望大家有空的时候能教一下我这个新手啥。谢谢

**Comment by cundong** [comment]
http://blog.it985.com/1808.html
http://my.oschina.net/cheneywangc/blog/192381
找了两篇文章给你

**Comment by jymgongzuo** [comment]
你做开发的时候也是这样做的吗？将android stdio编译的工程转换一下，再导入到Eclipse吗？ 谢谢

**Comment by jymgongzuo** [comment]
还是不行呀，搞不定呀！
